// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass AboutDialog : Windows.UI.Xaml.Controls.ContentDialog
    {
        AboutDialog();

        String ApplicationDisplayName { get; };
        String ApplicationVersion { get; };
    }
}
